### ISSUE TITLE
Setup script error

### ISSUE THREAD

**Issue by Keberen** [afterpay/afterpay-magento#25]
I just installed an update to Afterpay version 0.13.0.  This was done as part of a website rebuild.  The extension runs fine but currently everytime the cache runs the Afterpay extension tries to rerun the installation script and triggers and error.  

The error is as follows:
a:5:{i:0;s:243:"Error in file: "/chroot/home/angelbub/angelbub.com.au/html/app/code/community/Afterpay/Afterpay/sql/afterpay_setup/install-0.13.0.php" - SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'afterpay_shipped_api_queue' already exists";i:1;s:1092:"#0 /chroot/home/angelbub/angelbub.com.au/html/app/code/core/Mage/Core/Model/Resource/Setup.php(644): Mage::exception('Mage_Core', 'Error in file: ...')
#1 /chroot/home/angelbub/angelbub.com.au/html/app/code/core/Mage/Core/Model/Resource/Setup.php(421): Mage_Core_Model_Resource_Setup->_modifyResourceDb('install', '', '2.0.3')
#2 /chroot/home/angelbub/angelbub.com.au/html/app/code/core/Mage/Core/Model/Resource/Setup.php(327): Mage_Core_Model_Resource_Setup->_installResourceDb('2.0.3')
#3 /chroot/home/angelbub/angelbub.com.au/html/app/code/core/Mage/Core/Model/Resource/Setup.php(235): Mage_Core_Model_Resource_Setup->applyUpdates()
#4 /chroot/home/angelbub/angelbub.com.au/html/app/code/core/Mage/Core/Model/App.php(428): Mage_Core_Model_Resource_Setup::applyAllUpdates()
#5 /chroot/home/angelbub/angelbub.com.au/html/app/code/core/Mage/Core/Model/App.php(354): Mage_Core_Model_App->_initModules()
#6 /chroot/home/angelbub/angelbub.com.au/html/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#7 /chroot/home/angelbub/angelbub.com.au/html/index.php(83): Mage::run('', 'store')
#8 {main}";s:3:"url";s:1:"/";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:7:"default";}

Any help to resolve this would be appreciated.

**Comment by dbashyal** [comment]
@Keberen That's because they have already included create table in another file:
`app/code/community/Afterpay/Afterpay/sql/afterpay_setup/upgrade-0.7.3-0.8.0.php`

So, on file `app/code/community/Afterpay/Afterpay/sql/afterpay_setup/install-0.13.0.php` either delete:

```
$installer->run("
        CREATE TABLE `{$installer->getTable('afterpay/afterpay_shipped_api_queue')}` (
          `shipped_api_queue_id` INT(11) NOT NULL auto_increment,
          `payment_id` INT(11) NOT NULL,
          `tracking_number` VARCHAR(255),
          `courier` VARCHAR(255),
          `errors_count` INT(11),
          PRIMARY KEY  (`shipped_api_queue_id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    ");
```

Or wrap that on try..catch as below and refresh cache:

```
try {
    $installer->run("
        CREATE TABLE `{$installer->getTable('afterpay/afterpay_shipped_api_queue')}` (
          `shipped_api_queue_id` INT(11) NOT NULL auto_increment,
          `payment_id` INT(11) NOT NULL,
          `tracking_number` VARCHAR(255),
          `courier` VARCHAR(255),
          `errors_count` INT(11),
          PRIMARY KEY  (`shipped_api_queue_id`)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
    ");
} catch (Exception $e) {
    Mage::logException($e);
}

```

Good Luck as they don't seem to reply!

**Comment by Keberen** [comment]
Thankyou.  That solved the issue.

**Comment by dbashyal** [comment]
@Keberen Good to know it worked for you.
